# Generated by Django 2.0.4 on 2018-07-05 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
