# Generated by Django 2.0.4 on 2018-07-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
