# Generated by Django 2.0.4 on 2018-07-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_userinfo_now_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='now_time',
        ),
    ]
